# Generated by Django 5.1.3 on 2024-11-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('day_type', models.CharField(max_length=100)),
                ('day_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('day_rate', models.IntegerField()),
                ('privacy_check', models.BooleanField(default=False)),
                ('user_mail', models.EmailField(max_length=100)),
            ],
        ),
    ]
